apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  email: {{ .Values.secrets.pgadmin_email | b64enc | quote }}
  password: {{ .Values.secrets.pgadmin_password | b64enc | quote }}
