apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infrascore-ingress
  annotations:
    # Basic ingress configuration
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: infrascore-backend-backend-chart
            port:
              number: 80
  - host: pgadmin.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: infrascore-pgadmin-pgadmin-chart
            port:
              number: 80
