
apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
type: Opaque
data:
  # Assuming you might want to move this here too or keep it separate.
  # For now just complying with the existing deployment.yaml reference which expects 'api-key'.
  # Ideally you should have this in values.yaml under secrets too.
  api-key: {{ .Values.secrets.secret_key | b64enc | quote }} 
